// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnQ3PSb25cwwHtW0bimN97TbXOtuKEU9w',
    appId: '1:700976704324:web:45795fd208eab3db6bc511',
    messagingSenderId: '700976704324',
    projectId: 'ajelement-81875',
    authDomain: 'ajelement-81875.firebaseapp.com',
    storageBucket: 'ajelement-81875.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt9KtF9aHSdAykLJZex0ISOpsUyM5aj8g',
    appId: '1:700976704324:android:07be007123aa7d5e6bc511',
    messagingSenderId: '700976704324',
    projectId: 'ajelement-81875',
    storageBucket: 'ajelement-81875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjSvOMr7ocxLgQQYyCRNT4gK5aPa25h2g',
    appId: '1:700976704324:ios:e7ba54db5c674fe56bc511',
    messagingSenderId: '700976704324',
    projectId: 'ajelement-81875',
    storageBucket: 'ajelement-81875.appspot.com',
    iosBundleId: 'com.example.ffsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjSvOMr7ocxLgQQYyCRNT4gK5aPa25h2g',
    appId: '1:700976704324:ios:6bb0d49124317ed86bc511',
    messagingSenderId: '700976704324',
    projectId: 'ajelement-81875',
    storageBucket: 'ajelement-81875.appspot.com',
    iosBundleId: 'com.example.ffsmart.RunnerTests',
  );
}
